baseurl = "https://josharcher.uk"
disablePathToLower = false
languageCode = "en-gb"
title = "Josh Archer"
canonifyurls = true
paginate = 8

[params]
    description = "Musings, ramblings, tips, tricks and essays by Josh Archer. Oh, and photos. Always something new, occasionally something interesting."

[Author]
	name = "Josh Archer"
	email = "josh@jamail.co.uk"
	twitter = "josharcher"
	github = "puffinblue"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

disqusShortname = "puffinblue"

[blackfriday]
smartypants = false
smartDashes = false
angledQuotes = false
latexDashes = false
