baseurl = "https://www.josharcher.uk"
disablePathToLower = false
languageCode = "en-gb"
title = "Josh Archer"
paginate = 8
disqusShortname = "josharcher"
googleAnalytics = "UA-62812844-1"

[params]
    description = "Musings, ramblings, tips, tricks and essays by Josh Archer. Oh, and photos. Always something new, occasionally something interesting."

[Author]
	name = "Josh Archer"
	email = "josh@jamail.co.uk"
	twitter = "josharcher"
	github = "josharcheruk"
    gitlab  = "josharcher"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[blackfriday]
smartypants = false
smartDashes = false
angledQuotes = false
latexDashes = false

[markup.goldmark.renderer]
unsafe= true